name: interactions
version: 1.0-SNAPSHOT
main: interactions.plugin.Interactions
api-version: 1.19
authors: ["Grabsky"]
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.0
  - org.jetbrains.kotlinx:kotlinx-serialization-core:1.3.3
  - org.jetbrains.kotlinx:kotlinx-serialization-hocon:1.3.3